on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Install R libraries in renv
        uses: r-lib/actions/setup-renv@v2

      - name: Render # if it is a pull request
        if: github.event_name == 'pull_request'
        run: quarto render

      - name: Render and Publish # if you are pushing to main
        if: github.event_name == 'push'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

